title: Product
pages: false
files:
  sortable: true
fields:
  title:
    label: Title
    type:  text
    width: 3/4
  price:
    label: price
    type:  text
    width: 1/4
  tags:
    label: Tags
    type:  tags
    width: 3/4
  soldout:
    label: Product sold out
    type: switch
    text: 
    width: 1/4
  text:
    label: Text
    type:  textarea