title: Site
pages: default
fields:
  siteSettings:
    label: Site Settings
    type: headline
  title:
    label: Title
    type:  text
  author:
    label: Author
    type:  text
  description:
    label: Description
    type:  textarea
  keywords:
    label: Keywords
    type:  tags
  copyright:
    label: Copyright
    type:  textarea

  cartSettings:
    label: Payment Settings
    type: headline
  currency_code:
    label: Currency Code
    type:  text
    placeholder: EUR, USD, GBP…
    icon: money
    required: true
    width: 1/2
  currency_symbol:
    label: Currency Symbol
    type:  text
    placeholder: €, $, £…
    icon: money
    required: true
    width: 1/2
  stripe_secret_key:
    label: Stripe secret key
    type:  text
    icon: key
    required: true
    width: 1/2
  stripe_public_key:
    label: Stripe publishable key
    type:  text
    icon: key
    required: true
    width: 1/2
  stripe_testing_secret_key:
    label: Stripe testing secret key
    type:  text
    icon: key
    required: true
    width: 1/2
  stripe_testing_public_key:
    label: Stripe testing publishable key
    type:  text
    icon: key
    required: true
    width: 1/2
  sandbox:
      label: Stripe Sandbox
      type: switch
      text: Use Stripe test keys for debugging.
      width: 1/2